# test with
# docker run --rm -v (pwd):/goapp -e RUN=1 -e REPO=github.com/paddlesteamer/go-fuse-c golangci/build-runner goenvbuild

service:
  golangci-lint-version: 1.17.x
  prepare:
    - apt-get update && apt-get install -y libfuse-dev
    - make vendor

linters-settings:
  goimports:
    local-prefixes: github.com/paddlesteamer/go-fuse-c

linters:
  enable-all: true
  disable:
    - gochecknoglobals